<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $achievements = [
            // BUYER CATEGORY
            [
                'name' => 'First Steps',
                'slug' => 'first-steps',
                'description' => 'Make your first purchase on the marketplace',
                'icon' => '🎯',
                'category' => 'buyer',
                'tier' => 'bronze',
                'points' => 10,
                'wallet_reward' => 5.00,
                'requirements' => json_encode(['total_purchases' => 1]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Regular Shopper',
                'slug' => 'regular-shopper',
                'description' => 'Complete 10 purchases',
                'icon' => '🛒',
                'category' => 'buyer',
                'tier' => 'silver',
                'points' => 25,
                'wallet_reward' => 10.00,
                'requirements' => json_encode(['total_purchases' => 10]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Shopping Spree',
                'slug' => 'shopping-spree',
                'description' => 'Complete 50 purchases',
                'icon' => '🎁',
                'category' => 'buyer',
                'tier' => 'gold',
                'points' => 50,
                'wallet_reward' => 25.00,
                'requirements' => json_encode(['total_purchases' => 50]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Big Spender',
                'slug' => 'big-spender',
                'description' => 'Spend $500 total on the marketplace',
                'icon' => '💰',
                'category' => 'buyer',
                'tier' => 'gold',
                'points' => 75,
                'wallet_reward' => 50.00,
                'requirements' => json_encode(['total_spent' => 500]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'VIP Buyer',
                'slug' => 'vip-buyer',
                'description' => 'Spend $2,000 total - You\'re a valued customer!',
                'icon' => '👑',
                'category' => 'buyer',
                'tier' => 'platinum',
                'points' => 150,
                'wallet_reward' => 100.00,
                'requirements' => json_encode(['total_spent' => 2000]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Legendary Collector',
                'slug' => 'legendary-collector',
                'description' => 'Complete 200 purchases and spend over $5,000',
                'icon' => '💎',
                'category' => 'buyer',
                'tier' => 'diamond',
                'points' => 300,
                'wallet_reward' => 250.00,
                'requirements' => json_encode(['total_purchases' => 200, 'total_spent' => 5000]),
                'is_active' => true,
                'is_secret' => false,
            ],

            // SELLER CATEGORY
            [
                'name' => 'First Sale',
                'slug' => 'first-sale',
                'description' => 'Make your first sale as a seller',
                'icon' => '📦',
                'category' => 'seller',
                'tier' => 'bronze',
                'points' => 15,
                'wallet_reward' => 10.00,
                'requirements' => json_encode(['is_seller' => true, 'total_sales' => 1]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Rising Merchant',
                'slug' => 'rising-merchant',
                'description' => 'Complete 25 sales',
                'icon' => '📈',
                'category' => 'seller',
                'tier' => 'silver',
                'points' => 50,
                'wallet_reward' => 25.00,
                'requirements' => json_encode(['is_seller' => true, 'total_sales' => 25]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Profit Maker',
                'slug' => 'profit-maker',
                'description' => 'Generate $1,000 in total revenue',
                'icon' => '💵',
                'category' => 'seller',
                'tier' => 'gold',
                'points' => 100,
                'wallet_reward' => 50.00,
                'requirements' => json_encode(['is_seller' => true, 'total_revenue' => 1000]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Top Seller',
                'slug' => 'top-seller',
                'description' => 'Complete 100 sales and maintain high ratings',
                'icon' => '⭐',
                'category' => 'seller',
                'tier' => 'platinum',
                'points' => 200,
                'wallet_reward' => 100.00,
                'requirements' => json_encode(['is_seller' => true, 'total_sales' => 100, 'average_rating' => 4.5]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Marketplace Tycoon',
                'slug' => 'marketplace-tycoon',
                'description' => 'Generate $10,000+ in revenue - You run this place!',
                'icon' => '🏆',
                'category' => 'seller',
                'tier' => 'diamond',
                'points' => 500,
                'wallet_reward' => 500.00,
                'requirements' => json_encode(['is_seller' => true, 'total_revenue' => 10000]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Perfect Service',
                'slug' => 'perfect-service',
                'description' => 'Maintain 5.0 average rating with 50+ reviews',
                'icon' => '🌟',
                'category' => 'seller',
                'tier' => 'diamond',
                'points' => 300,
                'wallet_reward' => 200.00,
                'requirements' => json_encode(['is_seller' => true, 'average_rating' => 5.0, 'reviews_count' => 50]),
                'is_active' => true,
                'is_secret' => false,
            ],

            // SOCIAL CATEGORY
            [
                'name' => 'Conversation Starter',
                'slug' => 'conversation-starter',
                'description' => 'Send your first message',
                'icon' => '💬',
                'category' => 'social',
                'tier' => 'bronze',
                'points' => 5,
                'wallet_reward' => 2.00,
                'requirements' => json_encode(['messages_sent' => 1]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Communicator',
                'slug' => 'communicator',
                'description' => 'Send 50 messages',
                'icon' => '📨',
                'category' => 'social',
                'tier' => 'silver',
                'points' => 20,
                'wallet_reward' => 10.00,
                'requirements' => json_encode(['messages_sent' => 50]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Social Butterfly',
                'slug' => 'social-butterfly',
                'description' => 'Send 200 messages - You love to chat!',
                'icon' => '🦋',
                'category' => 'social',
                'tier' => 'gold',
                'points' => 50,
                'wallet_reward' => 25.00,
                'requirements' => json_encode(['messages_sent' => 200]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Helpful Reviewer',
                'slug' => 'helpful-reviewer',
                'description' => 'Leave 10 reviews',
                'icon' => '✍️',
                'category' => 'social',
                'tier' => 'silver',
                'points' => 25,
                'wallet_reward' => 15.00,
                'requirements' => json_encode(['reviews_count' => 10]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Review Master',
                'slug' => 'review-master',
                'description' => 'Leave 50 detailed reviews',
                'icon' => '📝',
                'category' => 'social',
                'tier' => 'gold',
                'points' => 75,
                'wallet_reward' => 40.00,
                'requirements' => json_encode(['reviews_count' => 50]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Community Leader',
                'slug' => 'community-leader',
                'description' => 'Send 500 messages and leave 75 reviews',
                'icon' => '👥',
                'category' => 'social',
                'tier' => 'platinum',
                'points' => 150,
                'wallet_reward' => 100.00,
                'requirements' => json_encode(['messages_sent' => 500, 'reviews_count' => 75]),
                'is_active' => true,
                'is_secret' => false,
            ],

            // SPECIAL CATEGORY
            [
                'name' => 'Early Adopter',
                'slug' => 'early-adopter',
                'description' => 'Join the platform in its first month',
                'icon' => '🚀',
                'category' => 'special',
                'tier' => 'gold',
                'points' => 100,
                'wallet_reward' => 50.00,
                'requirements' => json_encode(['account_age_days' => 1]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Veteran',
                'slug' => 'veteran',
                'description' => 'Be a member for 1 year',
                'icon' => '🎖️',
                'category' => 'special',
                'tier' => 'platinum',
                'points' => 200,
                'wallet_reward' => 100.00,
                'requirements' => json_encode(['account_age_days' => 365]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Secret Treasure',
                'slug' => 'secret-treasure',
                'description' => 'Found the hidden achievement! You\'re special!',
                'icon' => '🎁',
                'category' => 'special',
                'tier' => 'diamond',
                'points' => 500,
                'wallet_reward' => 1000.00,
                'requirements' => json_encode(['total_purchases' => 1, 'total_sales' => 1, 'messages_sent' => 100]),
                'is_active' => true,
                'is_secret' => true,
            ],
            [
                'name' => 'Jack of All Trades',
                'slug' => 'jack-of-all-trades',
                'description' => 'Be an active buyer, seller, and community member',
                'icon' => '🎭',
                'category' => 'special',
                'tier' => 'platinum',
                'points' => 250,
                'wallet_reward' => 150.00,
                'requirements' => json_encode([
                    'total_purchases' => 20,
                    'total_sales' => 20,
                    'reviews_count' => 20,
                    'messages_sent' => 100
                ]),
                'is_active' => true,
                'is_secret' => false,
            ],
            [
                'name' => 'Diamond Hands',
                'slug' => 'diamond-hands',
                'description' => 'Complete the ultimate challenge',
                'icon' => '💎',
                'category' => 'special',
                'tier' => 'diamond',
                'points' => 1000,
                'wallet_reward' => 2500.00,
                'requirements' => json_encode([
                    'total_purchases' => 100,
                    'total_spent' => 5000,
                    'total_sales' => 100,
                    'total_revenue' => 5000,
                    'average_rating' => 4.8
                ]),
                'is_active' => true,
                'is_secret' => true,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::create($achievement);
        }
    }
}
